### ISSUE TITLE
Using parquet files instead of loads of CSVs?

### ISSUE THREAD

**Issue by aleighbrown** [isaacvock/fastq2EZbakR#12]
Hi there - having you considered using parquet files instead of tons of chunky CSVs?

the intermediate files really eat space - I would imagine using parquet instead could be a quick swap to reduce disk usage (but honestly just a suggestion)

e.g..on a dataset of 23 samples for just an example result folder

```
du -sh results/rsem_csv/
120G	results/rsem_csv/
```

**Comment by isaacvock** [comment]
Reducing disk space is something I would like to work on. Parquet files will not be an easy drop in solution as they are still a somewhat niche file type supported by only a handful of libraries, meaning using them would require significant rewrites of large portions of the pipeline. I'll try and think of some other ways to reduce disk space usage.

A couple notes:

1. Currently, I try to judiciously use [Snakemake's temp() tag](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#protected-and-temporary-files) so that any intermediate files not necessary to include in the final output are deleted once the rules using them finish. Thus, a lot of the temporary csv files get deleted soon after they are created which should help to limit disk space usage a bit. The only non-temporary csv files that should be created (except the ones you showed an example for, see note 2 for discussion of those) are the read-by-read mutation counting information and the merged mutation counting + feature assignment table. I could mark the former as temp, as technically all of their information is found in the latter, which could help a bit.
2. The example you showed is not currently marked as temp() but should be as there is no reason to want to keep these csv files, so that's an oversight on my part. As an aside, these files come from the RSEM+ branch of the pipeline (i.e, `rsemp: True` was set in the config), which is a highly suboptimal branch for many reasons (slow, high RAM usage, etc.), and can be replaced with a combination of setting `Transcripts: True` in the config and using [EZbakR's isoform deconvolution](https://isaacvock.github.io/EZbakR/articles/EstimateFractions.html#isoform-deconvolution) strategy. This is all unpublished stuff too, so still experimental.
3. For large datasets with many samples, it might be best to run the pipeline separately on batches of samples, and only save the files you need from each run. The resulting separate cB files can either be merged post-hoc, or you can write them to a combined arrow dataset of parquet files and pass this to [EZbakR](https://isaacvock.github.io/EZbakR/articles/EstimateFractions.html#using-the-apache-arrow-backend).

**Comment by isaacvock** [comment]
I'll close this issue as the RSEM+ branch has been removed for now and I've added temp() flags in a number of places to try and cut down on disk space usage.
